CREATE TABLE IF NOT EXISTS `chaindb`.`users` (
  `iduser` CHAR(38) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;